"""baseline_schema

Revision ID: 682febd8daff
Revises: 
Create Date: 2026-05-08 22:06:54.832375

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '682febd8daff'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_telegram_id'), 'customers', ['telegram_id'], unique=True)
    op.create_table('email_blocklist',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), server_default='manual', nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('brand_color', sa.String(length=7), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('legal_entity_type', postgresql.ENUM('ip', 'ooo', 'self_employed', 'other', name='legal_entity_type'), nullable=True),
    sa.Column('legal_inn', sa.String(length=12), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('qrm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('qrm_api_login', sa.String(length=255), nullable=True),
    sa.Column('qrm_prod_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('white_label_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('smtp_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('refund_policy', sa.Text(), nullable=True),
    sa.Column('auto_publish_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', postgresql.ENUM('pending_moderation', 'active', 'suspended', name='organization_status'), server_default='pending_moderation', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_status', 'organizations', ['status'], unique=False)
    op.create_table('events',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capacity_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sold_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_card_url', sa.Text(), nullable=True),
    sa.Column('image_background_url', sa.Text(), nullable=True),
    sa.Column('custom_fields_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'pending_moderation', 'published', 'archived', 'rejected', name='event_status'), server_default='draft', nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_events_org_slug')
    )
    op.create_index('ix_events_org_status', 'events', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    op.create_index('ix_events_published_at', 'events', ['published_at'], unique=False)
    op.create_table('organization_balance',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('balance_kopecks', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', postgresql.ENUM('superadmin', 'organizer', 'scanner', 'cashier', 'support', name='user_role'), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_table('tariffs',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('capacity_limit', sa.Integer(), nullable=True),
    sa.Column('sold_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_complimentary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_event_id'), 'tariffs', ['event_id'], unique=False)
    op.create_index(op.f('ix_tariffs_organization_id'), 'tariffs', ['organization_id'], unique=False)
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', postgresql.ENUM('percent', 'fixed_amount', 'fixed_price', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('tariff_id', sa.UUID(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_affiliate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('affiliate_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_promo_codes_org_code')
    )
    op.create_index(op.f('ix_promo_codes_event_id'), 'promo_codes', ['event_id'], unique=False)
    op.create_index('ix_promo_codes_org_active', 'promo_codes', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_promo_codes_organization_id'), 'promo_codes', ['organization_id'], unique=False)
    op.create_table('reservations',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('custom_fields_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('items_subtotal_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('discount_kopecks', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('referrer_code', sa.String(length=64), nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'pending_payment', 'paid', 'cancelled', 'expired', name='reservation_status'), server_default='draft', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('consent_privacy', sa.Boolean(), nullable=False),
    sa.Column('consent_offer', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_reservations_customer_id'), 'reservations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reservations_event_id'), 'reservations', ['event_id'], unique=False)
    op.create_index('ix_reservations_event_status', 'reservations', ['event_id', 'status'], unique=False)
    op.create_index('ix_reservations_org_status', 'reservations', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_reservations_organization_id'), 'reservations', ['organization_id'], unique=False)
    op.create_index('ix_reservations_status_expires', 'reservations', ['status', 'expires_at'], unique=False)
    op.create_table('payments',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('qrmanager', 'complimentary', 'cash', name='payment_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='RUB', nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'cancelled', 'expired', 'refunded', 'partially_refunded', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('qr_url', sa.Text(), nullable=True),
    sa.Column('qr_image_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_amount_kopecks', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index('ix_payments_provider_payment', 'payments', ['provider', 'provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('promo_code_usages',
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('discount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promo_usages_code_email', 'promo_code_usages', ['promo_code_id', 'email'], unique=False)
    op.create_table('reservation_items',
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_reservation_items_qty_positive'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_items_reservation_id'), 'reservation_items', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_items_tariff_id'), 'reservation_items', ['tariff_id'], unique=False)
    op.create_table('balance_transactions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('commission_debit', 'topup', 'manual_adjustment', 'refund_credit', name='balance_transaction_type'), nullable=False),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('related_payment_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_transactions_organization_id'), 'balance_transactions', ['organization_id'], unique=False)
    op.create_index('ix_balance_tx_org_created', 'balance_transactions', ['organization_id', 'created_at'], unique=False)
    op.create_table('tickets',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=False),
    sa.Column('reservation_item_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('guest_first_name', sa.String(length=100), nullable=False),
    sa.Column('guest_last_name', sa.String(length=100), nullable=False),
    sa.Column('guest_index', sa.SmallInteger(), nullable=False),
    sa.Column('status', postgresql.ENUM('issued', 'checked_in', 'cancelled', 'refunded', name='ticket_status'), server_default='issued', nullable=False),
    sa.Column('is_complimentary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_user_id', sa.UUID(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_item_id'], ['reservation_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tickets_event_id'), 'tickets', ['event_id'], unique=False)
    op.create_index('ix_tickets_org_event_status', 'tickets', ['organization_id', 'event_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tickets_reservation_id'), 'tickets', ['reservation_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('related_payment_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_provider'), 'webhook_deliveries', ['provider'], unique=False)
    op.create_table('deposits',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.String(length=32), nullable=True),
    sa.Column('initial_amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('remaining_amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending_payment', 'active', 'partially_used', 'fully_used', 'expired', 'refunded', name='deposit_status'), server_default='pending_payment', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_to_iiko', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('iiko_order_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_organization_id'), 'deposits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deposits_ticket_id'), 'deposits', ['ticket_id'], unique=False)
    op.create_table('deposit_transactions',
    sa.Column('deposit_id', sa.UUID(), nullable=False),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('type', postgresql.ENUM('charge', 'refund', 'adjustment', name='deposit_transaction_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_transactions_deposit_id'), 'deposit_transactions', ['deposit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deposit_transactions_deposit_id'), table_name='deposit_transactions')
    op.drop_table('deposit_transactions')
    op.drop_index(op.f('ix_deposits_ticket_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_organization_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_webhook_deliveries_provider'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_tickets_reservation_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_index('ix_tickets_org_event_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_event_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_balance_tx_org_created', table_name='balance_transactions')
    op.drop_index(op.f('ix_balance_transactions_organization_id'), table_name='balance_transactions')
    op.drop_table('balance_transactions')
    op.drop_index(op.f('ix_reservation_items_tariff_id'), table_name='reservation_items')
    op.drop_index(op.f('ix_reservation_items_reservation_id'), table_name='reservation_items')
    op.drop_table('reservation_items')
    op.drop_index('ix_promo_usages_code_email', table_name='promo_code_usages')
    op.drop_table('promo_code_usages')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index('ix_payments_provider_payment', table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_reservations_status_expires', table_name='reservations')
    op.drop_index(op.f('ix_reservations_organization_id'), table_name='reservations')
    op.drop_index('ix_reservations_org_status', table_name='reservations')
    op.drop_index('ix_reservations_event_status', table_name='reservations')
    op.drop_index(op.f('ix_reservations_event_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_customer_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_promo_codes_organization_id'), table_name='promo_codes')
    op.drop_index('ix_promo_codes_org_active', table_name='promo_codes')
    op.drop_index(op.f('ix_promo_codes_event_id'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_tariffs_organization_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_event_id'), table_name='tariffs')
    op.drop_table('tariffs')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('organization_balance')
    op.drop_index('ix_events_published_at', table_name='events')
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index('ix_events_org_status', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_organizations_status', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('email_blocklist')
    op.drop_index(op.f('ix_customers_telegram_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # Явный drop ENUM-типов (Alembic autogenerate не умеет их чистить)
    for enum_name in (
        'balance_transaction_type',
        'deposit_status',
        'deposit_transaction_type',
        'discount_type',
        'event_status',
        'legal_entity_type',
        'organization_status',
        'payment_provider',
        'payment_status',
        'reservation_status',
        'ticket_status',
        'user_role',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
